WebUI/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CodeFirst.Models;
using Core.Services;
using Microsoft.AspNet.Identity.Owin;
using WebUI.Models;
using WebUI.Models.Brand;

namespace WebUI.Controllers
{
    public class BrandsController : Controller
    {
        //private ApplicationContext db
        //{
        //    get { return HttpContext.GetOwinContext().Get<ApplicationContext>(); }
        //}
        private IBrandService _brandService;

        public BrandsController(IBrandService brandService)
        {
            _brandService = brandService;
        }

        // GET: Brands
        public async Task<ActionResult> Index()
        {
            IndexModel model = new IndexModel
            {
                Brands = await _brandService.GetAllBrands()
            };
            return View(model);
        }

        // GET: Brands/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = await _brandService.GetBrandById(id);
            AddEditModel brandViewModel = new AddEditModel
            {
                Id =  brand.Id,
                Name = brand.Name,
                Description = brand.Description
            };
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brandViewModel);
        }

        // GET: Brands/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create( AddEditModel brandViewModel)
        {
            if (ModelState.IsValid)
            {
               Brand brand = new Brand
               {
                   Description = brandViewModel.Description,
                   Name = brandViewModel.Name
               };
               await _brandService.AddOrUpdate(brand);
                return RedirectToAction("Index");
            }

            return View(brandViewModel);
        }

        // GET: Brands/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = await _brandService.GetBrandById(id);
            if (brand != null)
            {
                AddEditModel brandViewModel = new AddEditModel
                {
                    Id = brand.Id,
                    Name = brand.Name,
                    Description = brand.Description
                };
                return View(brandViewModel);
            }
            else 
            {
                return HttpNotFound();
            }
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AddEditModel brandViewModel)
        {
            if (ModelState.IsValid)
            {
                Brand brand = await _brandService.GetBrandById(brandViewModel.Id);
                if (brand != null)
                {
                    brand.Name = brandViewModel.Name;
                    brand.Description = brandViewModel.Description;
                    await _brandService.AddOrUpdate(brand);
                    return RedirectToAction("Index");
                }
                else return HttpNotFound();
            }
            return View(brandViewModel);
        }

        // GET: Brands/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = await _brandService.GetBrandById(id);
            if (brand != null)
            {
                AddEditModel brandViewModel = new AddEditModel
                {
                    Id = brand.Id,
                    Name = brand.Name,
                    Description = brand.Description
                };
                return View(brandViewModel);
            }
            else 
            {
                return HttpNotFound();
            }
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Brand brand = await _brandService.GetBrandById(id);
            if (brand != null)
            {
                await _brandService.Remove(id);
                return RedirectToAction("Index");
            }
            else return HttpNotFound();
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

WebUI/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CodeFirst.Models;
using Core.Services;
using Microsoft.AspNet.Identity.Owin;

namespace WebUI.Controllers
{
    public class OrdersController : Controller
    {
        //private ApplicationContext db
        //{
        //    get { return HttpContext.GetOwinContext().Get<ApplicationContext>(); }
        //}
        private IOrderService _orderService;

        public OrdersController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        // GET: Orders
        public async Task<ActionResult> Index()
        {
            return View(await _orderService.GetAllOrders());
        }

        // GET: Orders/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await _orderService.GetOrderById(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "DeliveryAddress,DeliveryTime")] Order order)
        {
            if (ModelState.IsValid)
            {
               await _orderService.AddOrUpdate(order);
                return RedirectToAction("Index");
            }

            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await _orderService.GetOrderById(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
           // [Bind(Include = "Id,UserId,DeliveryAddress,DeliveryTime")]
        Order order)
        {
            if (ModelState.IsValid)
            {
                await _orderService.AddOrUpdate(order);
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await _orderService.GetOrderById(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _orderService.Remove(id);
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

WebUI/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CodeFirst.Models;
using Data.Identity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class RolesController : Controller
    {
        private ApplicationRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationRoleManager>();
            }
        }

        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(CreateRoleModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await RoleManager.CreateAsync(new ApplicationRole
                {
                    Name = model.Name,
                    Description = model.Description
                });
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Что-то пошло не так");
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Edit(string id)
        {
            ApplicationRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                return View(new EditRoleModel { Id = role.Id, Name = role.Name, Description = role.Description });
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<ActionResult> Edit(EditRoleModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationRole role = await RoleManager.FindByIdAsync(model.Id);
                if (role != null)
                {
                    role.Description = model.Description;
                    role.Name = model.Name;
                    IdentityResult result = await RoleManager.UpdateAsync(role);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Что-то пошло не так");
                    }
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Delete(string id)
        {
            ApplicationRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await RoleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }
    }
}

WebUI/Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CodeFirst.Models;
using Core.Services;
using Microsoft.AspNet.Identity.Owin;
using WebUI.Models.Stocks;

namespace WebUI.Controllers
{
    public class StocksController : Controller
    {
        private readonly IStockService _stockService;
        private readonly IWarehouseService _warehouseService;

        public StocksController(IStockService stockService,  IWarehouseService warehouseService)
        {
            _stockService = stockService;
            _warehouseService = warehouseService;
        }

        // GET: Stocks
        public async Task<ActionResult> Index()
        {
            IndexModel model = new IndexModel
            {
                Stocks = await _stockService.GetAllStocksWithProducts()
            };
            return View(model);
        }
        [HttpGet]
        public async Task<ActionResult> AddEdit(int? productId)
        {
            if (productId == null) return HttpNotFound();
            var stocks = await _stockService.GetAllStocksByProductId(productId);
            var warehouses = await _warehouseService.GetAllWarehouses();
            AddEditModel model = new AddEditModel();
            if (stocks == null || stocks.Count == 0)
            {
                foreach (var warehouse in warehouses)
                {
                    StockHolder stockHolder = new StockHolder
                    {
                        ProductId = productId.Value,
                        CurrentNumberOfProducts = 0,
                        WarehouseId = warehouse.Id,
                        WarehouseAddress = warehouse.Address
                    };
                    model.StockHolders.Add(stockHolder);
                }
            }
            else
            {
                foreach (var stock in stocks)
                {
                    var warehouse = warehouses.FirstOrDefault(w => w.Id == stock.WarehouseId);
                    StockHolder stockHolder = new StockHolder
                    {
                        ProductId = stock.ProductId,
                        CurrentNumberOfProducts = stock.NumberOfProducts,
                        WarehouseId = stock.WarehouseId,
                        Id = stock.Id,
                        WarehouseAddress = warehouse.Address
                    };
                    model.StockHolders.Add(stockHolder);
                }
            }
            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddEdit(AddEditModel model)
        {
            if (ModelState.IsValid)
            {
                foreach (var stockHolder in model.StockHolders)
                {
                    Stock stock = new Stock
                    {
                        Id = stockHolder.Id,
                        NumberOfProducts = stockHolder.CurrentNumberOfProducts + stockHolder.CountToAdd,
                        ProductId = stockHolder.ProductId,
                        WarehouseId = stockHolder.WarehouseId
                    };
                    await _stockService.AddOrUpdate(stock);
                }
                return RedirectToAction("Index", "Products");
            }
            return View(model);

        }
      
}
}

WebUI/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("headerScripts",false)
    @RenderSection("Links", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>   @Html.ActionLink("Аккаунты", "Index", "Account")</li>*@

                    <li> @Html.ActionLink("Брэнды", "Index", "Brands")</li>
                    <li> @Html.ActionLink("Заказы", "Index", "Orders")</li>
                    <li> @Html.ActionLink("Категории", "Index", "Categories")</li>
                    <li> @Html.ActionLink("Корзины", "Index", "Baskets")</li>
                    <li> @Html.ActionLink("Курьеры", "Index", "Couriers")</li>
                    <li> @Html.ActionLink("Наличие", "Index", "Stocks")</li>
                    <li> @Html.ActionLink("Подкатегории", "Index", "Subcategories")</li>
                    <li> @Html.ActionLink("Продукты", "Index", "Products")</li>
                    <li> @Html.ActionLink("Роли", "Index", "Roles")</li>
                    <li> @Html.ActionLink("Склады", "Index", "Warehouse")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
@*@Scripts.Render("~/bundles/ko")*@
    @RenderSection("scripts", required: false)
    

</body>
</html>

WebUI/Views/Shared/_СustomerLayout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_СustomerLayout</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Catalog/_customerLayout.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Catalog/Customer.css">
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/ko")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/knockout-2.2.1.js" type="text/javascript"></script>
</head>
<body>
    <div id="wrapper">
        <!-- Верхняя панель -->
        <div class="panel-top">
            <div class="center clearfix">
                <div class="social">
                    <a href="#" class="s-fb">&nbsp;</a>
                    <a href="#" class="s-dribble">&nbsp;</a>
                    <a href="#" class="s-tw">&nbsp;</a>
                    <a href="#" class="s-mail">&nbsp;</a>
                    <a href="#" class="s-vimeo">&nbsp;</a>
                </div>
                <div class="basket" data-bind="click: function(data,event){set_modal_visible('.cart_content')}">
                    <a href="#"><span data-bind="text:cart().total_count"></span><span>&nbsp;in</span></a>
                </div>
                <div class="login">
                    <a href="#">Login</a>
                    <span>/</span>
                    <a href="#">Register</a>
                </div>
            </div>
        </div>
        <!-- // Верхняя панель -->
        <!-- Шапка сайта -->
        <div id="header" class="center clearfix">
            <!-- Логотип -->
            <div id="logo" class="left">
                <a href="#">
                    <img src="~/Content/images/logo.png" height="60" width="61" alt="" />
                    <span>Store</span>
                </a>
            </div>
            <!-- // Логотип -->
            <!-- Навигация -->
            <ul class="nav right clearfix">
                <li class="active"><a href="#">HOME</a></li>
                <li><a href="#">CD’s</a></li>
                <li><a href="#">DVD’s</a></li>
                <li><a href="#">NEWS</a></li>
                <li><a href="#">PORTFOLIO</a></li>
                <li><a href="#">CONTACT US</a></li>
            </ul>
            <!-- // Навигация -->
        </div>

        <div id="home">
            <div class="home-bg">
                <div class="center">
                    <a href="/" class="link-home">&nbsp;</a>
                    <h2 class="title-home">SHOP - SIDEBAR ON THE RIGHT</h2>
                    <ul class="breadcrumbs clearfix">
                        <li><a href="#">Home</a><span class="sp">&raquo;</span></li>
                        <li><a href="#">Shop</a><span class="sp">&raquo;</span></li>
                        <li><span>Sidebar on the right</span></li>
                    </ul>
                </div>
            </div>
        </div>
        @RenderSection("Categories",false);
        <!-- // Шапка сайта -->
    </div>
    

        <div class="render-body">
            @RenderBody()
        </div>

        @Scripts.Render("~/bundles/bootstrap")
</body>
</html>*